newsite/my_project/books/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'books'

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    #/books/2/
    url(r'^(?P<book_id>[0-9]+)/$', views.detail, name = 'detail'),
    
]

newsite/my_project/my_project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls import url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^books/', include('books.urls')),
]

newsite/my_project/books/models.py
from django.db import models

class Book(models.Model):

    def __str__(self):
        return self.name +'-'+ self.author
        
    name = models.CharField(max_length = 100)
    author = models.CharField(max_length = 100)
    price = models.CharField(max_length = 100)
    typee = models.CharField(max_length = 100)

newsite/my_project/books/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Book
from django.http import Http404


def index(request):
    all_books = Book.objects.all()
    
    context ={
        'all_books': all_books

    }
    return render(request,'books/index.html', context)

def detail(request,book_id):
    try:
        book = Book.objects.get(id = book_id)

    except Book.DoesNotExist:

        raise Http404("this book does not exist")


    return render(request,'books/detail.html',{'book':book})


 

newsite/my_project/books/templates/books/detail.html
<h1>{{book.name}}</h1>
<h4>{{book.author}}</h4>

newsite/my_project/books/templates/books/index.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'books/style.css' %}" type="text/css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>books</title>
</head>
<body>
    <nav class = "navbar navbar-inverse">
        <div class="container-fluid">
            <a class="navbar-brand"href="{% url 'books:index' %}">The books store</a>
        </div>
    </nav>
    <ul>
        {% for book in all_books %}
            <li>
                <a href="{% url 'books:detail' book.id %}">{{book.name}}</a>
    
            </li>
        {% endfor %}
    
    </ul>
    
</body>
</html>